### ISSUE TITLE
Broken pope image :(

### ISSUE THREAD

**Issue by hucklebridge** [dustpancake/e-bot#15]
https://github.com/dustpancake/e-bot/blob/d54844bb37be2f0d6b9c03e85a9dfa2000cdd2cd/data/popelist.txt#L56

**Comment by fjebaker** [comment]
That's number 56 (55 taking account of 0) in the list -- the URL seems to resolve fine, so we'll just keep an eye on it in the chat.

**Comment by fjebaker** [comment]
So this is related to the nature of discord's auto-image embedding, and basically, since we've included text, it doesn't *always* resolve the images correctly.

We can fix this by explicitly creating a `discord.Embed` and giving it an image and the text separately. @hucklebridge I don't know if you fancy giving that a try?

**Comment by fjebaker** [comment]
Closing since stale.
